### ISSUE TITLE
Lemmy API changes

### ISSUE THREAD

**Issue by dessalines** [eiknat/lemmy-client#7]
Just a note, that there will be some API changes around how edits, deletes, removes, locks, stickies etc work, once this PR gets merged: https://github.com/LemmyNet/lemmy/pull/997

Viewing a git diff of the `docs/src/contributing_websocket_http_api` will show these changes.

**Comment by 5HT2** [comment]
Thanks for the heads up!

**Comment by eiknat** [comment]
need to double check but this should be taken care of

**Comment by dessalines** [comment]
Cool, I'll close this. Probably the best way to be notified of the changes, is by watching https://github.com/lemmynet/lemmy-js-client , which I'll pretty much only update for API changes.
